export declare const theme: {
    colors: {
        whiteAlpha: string[];
        blackAlpha: string[];
        grays: string[];
        reds: string[];
        oranges: string[];
        yellows: string[];
        greens: string[];
        teals: string[];
        blues: string[];
        cyans: string[];
        purples: string[];
        pinks: string[];
        transparent: string;
        black: string;
        white: string;
        gray: string;
        red: string;
        orange: string;
        yellow: string;
        green: string;
        teal: string;
        blue: string;
        cyan: string;
        purple: string;
        pink: string;
        primary: string;
        main: string;
        error: string;
    };
    fontSizes: number[];
    space: number[];
};
export declare type ThemeType = typeof theme;
